doctrine:
    dbal:
        default_connection: film
        connections:
            film:
                url: '%env(resolve:FILM_DATABASE_URL)%'
            front:
                url: '%env(resolve:FRONT_DATABASE_URL)%'
            graber:
                url: '%env(resolve:GRABER_DATABASE_URL)%'

    orm:
        default_entity_manager: film
        auto_generate_proxy_classes: true
        entity_managers:
            film:
                connection: film
                mappings:
                    Film:
                        alias: Film
                        is_bundle: false
                        prefix: 'App\Domain\Common\Domain\Entity\Base\Film'
                        dir: '%kernel.project_dir%/src/Domain/Common/Domain/Entity/Base/Film'
            front:
                connection: front
                mappings:
                    Front:
                        alias: Front
                        is_bundle: false
                        prefix: 'App\Domain\Common\Domain\Entity\Base\Front'
                        dir: '%kernel.project_dir%/src/Domain/Common/Domain/Entity/Base/Front'
            graber:
                connection: graber
                mappings:
                    Graber:
                        alias: Graber
                        is_bundle: false
                        prefix: 'App\Domain\Common\Domain\Entity\Base\Graber'
                        dir: '%kernel.project_dir%/src/Domain/Common/Domain/Entity/Base/Graber'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system