monolog:
    channels:
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                level: error
                type: stream
                channels: ["!event"]
                path: "%kernel.logs_dir%/%kernel.environment%.log"
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!http_client"]

when@test:
    monolog:
        handlers:
            main:
                handler: nested
                action_level: error
                channels: ["!event"]
                type: fingers_crossed
                excluded_http_codes: [404, 405]

            nested:
                type: stream
                level: debug
                path: "%kernel.logs_dir%/%kernel.environment%.log"

when@prod:
    monolog:
        handlers:
            main:
                buffer_size: 50
                handler: nested
                action_level: error
                type: fingers_crossed
                excluded_http_codes: [404, 405]
            nested:
                type: stream
                level: debug
                path: php://stderr
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                path: php://stderr
                channels: [deprecation]