parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    bind:
        $entityManagerFront: '@doctrine.orm.front_entity_manager'
        $entityManagerGraber: '@doctrine.orm.graber_entity_manager'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'